# Компилятор
CXX = g++

# Опции компиляции и линковки
CXXFLAGS = -std=c++11 -Wall

# Имя исполняемого файла
TARGET = sap_game

# Исходные файлы
SRCS = Sap.cpp main.cpp

# Объектные файлы
OBJS = $(SRCS:.cpp=.o)

# Цель по умолчанию
all: $(TARGET)

# Цель для сборки исполняемого файла
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Правило для компиляции cpp файлов в объектные файлы
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

# Цель для очистки собранных файлов
clean:
	rm -f $(TARGET) $(OBJS)*.o